// generated by stomptalkgen.js 2022-03-19T14:16:57.888Z
#ifndef stomptalk_header_h
#define stomptalk_header_h

#include "stomptalk/type.h"

static const uint64_t st_header_none = 0ULL;
static const uint64_t st_header_accept_version = 17730939333743088192ULL;
static const uint64_t st_header_ack = 16655369259664635522ULL;
static const uint64_t st_header_amqp_message_id = 13655801309941251534ULL;
static const uint64_t st_header_amqp_type = 8534956936704544159ULL;
static const uint64_t st_header_app_id = 15100076151578546910ULL;
static const uint64_t st_header_auto_delete = 6579649577394426104ULL;
static const uint64_t st_header_cluster_id = 16998084326538976157ULL;
static const uint64_t st_header_content_encoding = 10065166714832659144ULL;
static const uint64_t st_header_content_length = 3272324617478434429ULL;
static const uint64_t st_header_content_type = 1102772570596966965ULL;
static const uint64_t st_header_correlation_id = 11664028683362252763ULL;
static const uint64_t st_header_delivery_mode = 16919695974902994843ULL;
static const uint64_t st_header_destination = 16012153851639099583ULL;
static const uint64_t st_header_durable = 11702629850652017384ULL;
static const uint64_t st_header_expiration = 6003257886304494632ULL;
static const uint64_t st_header_expires = 12804369191422512899ULL;
static const uint64_t st_header_heart_beat = 12779275509635172402ULL;
static const uint64_t st_header_host = 4645455097838390639ULL;
static const uint64_t st_header_id = 628021283683842752ULL;
static const uint64_t st_header_login = 272289342528891346ULL;
static const uint64_t st_header_message = 6080987277291999908ULL;
static const uint64_t st_header_message_id = 6622717075092730054ULL;
static const uint64_t st_header_passcode = 11049069972726166461ULL;
static const uint64_t st_header_persistent = 1798157792242887456ULL;
static const uint64_t st_header_prefetch_count = 12434234952676628196ULL;
static const uint64_t st_header_priority = 17705596872970477193ULL;
static const uint64_t st_header_receipt = 17938850111118753539ULL;
static const uint64_t st_header_receipt_id = 3013261859695384359ULL;
static const uint64_t st_header_redelivered = 451708706259355272ULL;
static const uint64_t st_header_reply_to = 1959226419108500035ULL;
static const uint64_t st_header_requeue = 8012801732013360479ULL;
static const uint64_t st_header_server = 8256460951725924050ULL;
static const uint64_t st_header_session = 4369270734135252951ULL;
static const uint64_t st_header_subscription = 12139869593857250260ULL;
static const uint64_t st_header_timestamp = 6763441490543064067ULL;
static const uint64_t st_header_transaction = 4864123051784605667ULL;
static const uint64_t st_header_user_id = 3577555360522733048ULL;
static const uint64_t st_header_version = 13502572527641750071ULL;
static const uint64_t st_header_dead_letter_exchange = 1154572314406690607ULL;
static const uint64_t st_header_dead_letter_routing_key = 16438019653966889374ULL;
static const uint64_t st_header_max_length = 461239285347903895ULL;
static const uint64_t st_header_max_length_bytes = 10922518658645538165ULL;
static const uint64_t st_header_max_priority = 7931745217912277023ULL;
static const uint64_t st_header_message_ttl = 14310794223520664812ULL;
static const uint64_t st_header_original_exchange = 11773222124439154373ULL;
static const uint64_t st_header_original_routing_key = 1051592613767519200ULL;
static const uint64_t st_header_queue_name = 17916707561557856359ULL;
static const uint64_t st_header_queue_type = 2945278644365412388ULL;
static const uint64_t st_header_unknown = 18446744073709551615ULL;

#endif // stomptalk_header_h
