// generated by stomptalkgen.js 2022-03-19T14:16:57.870Z
#ifndef stomptalk_method_h
#define stomptalk_method_h

#include "stomptalk/type.h"

static const uint64_t st_method_none = 0ULL;
static const uint64_t st_method_abort = 4952805421744087193ULL;
static const uint64_t st_method_ack = 18028685673639592546ULL;
static const uint64_t st_method_begin = 1880872660716167550ULL;
static const uint64_t st_method_commit = 10536344083233345820ULL;
static const uint64_t st_method_connect = 13878768130668514073ULL;
static const uint64_t st_method_connected = 16993161426147750448ULL;
static const uint64_t st_method_disconnect = 14058969080426016363ULL;
static const uint64_t st_method_error = 11299948525800672273ULL;
static const uint64_t st_method_message = 13224981968854399236ULL;
static const uint64_t st_method_nack = 15675817292214105414ULL;
static const uint64_t st_method_receipt = 9277173349717397475ULL;
static const uint64_t st_method_send = 4760784348760774959ULL;
static const uint64_t st_method_stomp = 17356079153092702330ULL;
static const uint64_t st_method_subscribe = 15907597525158645283ULL;
static const uint64_t st_method_unsubscribe = 15537248877446182102ULL;
static const uint64_t st_method_unknown = 18446744073709551615ULL;

#endif // stomptalk_method_h
