#ifndef stomptalk_method_h
#define stomptalk_method_h

// generated by stomptalkgen.js 2022-03-15T11:25:09.501Z
enum stomptalk_method {
	st_method_none = 0ULL,
	st_method_abort = 4952805421744087193ULL,
	st_method_ack = 18028685673639592546ULL,
	st_method_begin = 1880872660716167550ULL,
	st_method_commit = 10536344083233345820ULL,
	st_method_connect = 13878768130668514073ULL,
	st_method_connected = 16993161426147750448ULL,
	st_method_disconnect = 14058969080426016363ULL,
	st_method_error = 11299948525800672273ULL,
	st_method_message = 13224981968854399236ULL,
	st_method_nack = 15675817292214105414ULL,
	st_method_receipt = 9277173349717397475ULL,
	st_method_send = 4760784348760774959ULL,
	st_method_stomp = 17356079153092702330ULL,
	st_method_subscribe = 15907597525158645283ULL,
	st_method_unsubscribe = 15537248877446182102ULL,
	st_method_unknown = 18446744073709551615ULL
};

#endif // stomptalk_method_h
