name: macos
on: [push, pull_request]

jobs:
  build:
    name: macOS Build
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Setup build environment
        run: |
          # Проверяем наличие CMake и Ninja
          echo "Checking build tools..."
          
          if command -v cmake &> /dev/null; then
            echo "✅ CMake found: $(cmake --version | head -1)"
          else
            echo "❌ CMake not found, installing..."
            brew install cmake
          fi
          
          if command -v ninja &> /dev/null; then
            echo "✅ Ninja found: $(ninja --version)"
          else
            echo "❌ Ninja not found, installing..."
            brew install ninja
          fi
          
          echo "✅ C++ compiler: $(c++ --version | head -1)"

      - name: Configure CMake
        run: |
          cmake -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror" \
            -DSTOMPTALK_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --verbose

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
