name: windows
on: [push, pull_request]

jobs:
  build:
    name: Windows Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -DCMAKE_CXX_FLAGS="/W4 /WX" -DSTOMPTALK_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --verbose

      - name: Run tests
        run: ctest --test-dir build --output-on-failure -C ${{ matrix.build_type }}
